version: '2.1'

services:
  r:
    image: rl-04
    build: .
    ports:
      - 8787:8787 # For rocker/tidyverse
    volumes:
      - ./output:/app/output
    stdin_open: true
    tty: true
    environment:
      - DISABLE_AUTH=true # if using rocker/tidyverse
